spring.application.name=messages
spring.datasource.url=jdbc:postgresql://localhost:5432/messages
spring.datasource.username=postgres
spring.datasource.password=aryan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true