spring.application.name=messages
spring.datasource.url=jdbc:postgresql://localhost:5432/messages
spring.datasource.username=postgres
spring.datasource.password=aryan

jwt.secret=aa6415359f42b4da9c1569323e521dfd9ce97d3921b7fd6085764035ed18b178
jwt.access-token-expiration=900000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true